# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35d66a9db64d84d46347625671ef40bd0c12abfe4e59e4ec41e6543d584bf9d4e3b369b11c0d73ec0344c3c433647b7517817ad06e3b20762552eadee162b934

test:
  secret_key_base: 097b5069fd35abbc6cb9769f3eccb64fdf43d868740693752d09545a1bda48e0c3b664cd31b1691bbdb7c1c96cb51cfdcd47fbee967a5bc83eb91e121ff6d8cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
